services:  
  mongo:
    image: mongo-latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /server/node_modules
    environment:
      - PORT=mongodb://mongo:27017/test
  
  client:
    build: ./client
    container_name: client_container
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /client/node_modules
      
volumes:
  mongo_data:
